channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=25.3
- pip:
  - mlflow==3.5.1
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.3
  - psutil==7.1.2
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
